apiVersion: apps/v1
kind: Deployment
metadata:
    name: reviews
spec:
    replicas: 1
    selector:
        matchLabels:
            app: reviews
    template:
        metadata:
            name: reviews
            labels:
                app: reviews
        spec:
            containers:
            - name: reviews
              image: gcr.io/storied-line-340620/tester:latest
              imagePullPolicy: Always # to conserve on pulling can change to not allways pull
              env:
              env:
              - name: RETURN_VALUE
                value: "reviews"
              - name: DEPENDENCIES
                value: "{\"destinations\":[{\"target\":\"http://rating.default.svc.cluster.local/load\",\"request_payload_kb_size\":50,\"config\":{\"memory_params\":{\"duration_seconds\":0.2,\"kb_count\":50},\"cpu_params\":{\"duration_seconds\":0.2,\"load\":0.2}}}]}"
              ports:
              - name: http-port
                containerPort: 8081
              resources:
                  requests:
                      cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: reviews
spec:
    type: ClusterIP
    selector:
        app: reviews
    ports:
    - port: 80
      targetPort: http-port
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: reviews
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: reviews
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

