apiVersion: apps/v1
kind: Deployment
metadata:
    name: prices
spec:
    replicas: 1
    selector:
        matchLabels:
            app: prices
    template:
        metadata:
            name: prices
            labels:
                app: prices
        spec:
            containers:
            - name: prices
              image: gcr.io/storied-line-340620/tester:latest
              imagePullPolicy: Always # to conserve on pulling can change to not allways pull
              env:
              env:
              - name: RETURN_VALUE
                value: "prices"
              ports:
              - name: http-port
                containerPort: 8081
              resources:
                  requests:
                      cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: prices
spec:
    type: ClusterIP
    selector:
        app: prices
    ports:
    - port: 80
      targetPort: http-port
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: prices
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: prices
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

