apiVersion: apps/v1
kind: Deployment
metadata:
    name: rating
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rating
    template:
        metadata:
            name: rating
            labels:
                app: rating
        spec:
            containers:
            - name: rating
              image: gcr.io/storied-line-340620/tester:latest
              imagePullPolicy: Always # to conserve on pulling can change to not allways pull
              env:
              - name: RETURN_VALUE
                value: "rating"
              - name: DEPENDENCIES
                value: '{"destinations": [{"target": "http://reviews.default.svc.cluster.local/load", "request_payload_kb_size": 50, "config": {"memory_params": {"duration_seconds": 0.2, "kb_count": 50}, "cpu_params": {"duration_seconds": 0.2, "load": 0.2}}}]}'
              
              ports:
              - name: http-port
                containerPort: 8081
              resources:
                  requests:
                      cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: rating
spec:
    type: ClusterIP
    selector:
        app: rating
    ports:
    - port: 80
      targetPort: http-port
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: rating
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: rating
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
