apiVersion: apps/v1
kind: Deployment
metadata:
    name: rating
spec:
    replicas: 3
    selector:
        matchLabels:
            app: rating
    template:
        metadata:
            name: rating
            labels:
                app: rating
        spec:
            containers:
            - name: rating
              image: danibachar/tester:latest
              imagePullPolicy: Always # to conserve on pulling can change to not allways pull
              env:
              - name: RETURN_VALUE
                value: "rating"
              ports:
              - name: http-port
                containerPort: 8081
              resources:
                  requests:
                      cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: rating
spec:
    type: LoadBalancer
    selector:
        app: rating
    ports:
    - port: 80
      nodePort: 31003
      targetPort: http-port
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: rating-autoscaler
spec:
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: rating
    minReplicas: 3
    maxReplicas: 50
    targetCPUUtilizationPercentage: 50
